In [1]:
import numpy as np
from sklearn.metrics import silhouette_score
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import os
os.chdir(r"C:\Training\Academy\Statistics (Python)\Datasets")
from sklearn.cluster import DBSCAN

In [2]:
milk = pd.read_csv("milk.csv",index_col=0)
scaler = StandardScaler().set_output(transform='pandas')
milkscaled=scaler.fit_transform(milk)
clust_DB = DBSCAN(eps=1, min_samples=4)
clust_DB.fit(milkscaled)
print(clust_DB.labels_)
print(len(set(clust_DB.labels_)))

[ 0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0  0 -1 -1 -1 -1 -1 -1 -1 -1
 -1]
2

In [3]:
eps_range = [0.2,0.4,0.6,1]
mp_range = [2,3,4,5]
cnt = 0
a =[]
for i in eps_range:
    for j in mp_range:
        clust_DB = DBSCAN(eps=i, min_samples=j)
        clust_DB.fit(milkscaled.iloc[:,:5])
        if len(set(clust_DB.labels_)) > 2:
            cnt = cnt + 1
            milkscaled['Clust'] = clust_DB.labels_
            milk_scl_inliers = milkscaled[milkscaled['Clust']!=-1]
            sil_sc = silhouette_score(milk_scl_inliers.iloc[:,:-1],
                             milk_scl_inliers.iloc[:,-1])
            a.append([cnt,i,j,sil_sc])
            print(i,j,sil_sc)
    
a = np.array(a)
pa = pd.DataFrame(a,columns=['Sr','eps','min_pt','sil'])
print("Best Paramters:")
pa[pa['sil'] == pa['sil'].max()]

0.4 2 0.6518937593821541
0.4 3 0.538518035246956
0.6 2 0.5934459505692156
0.6 3 0.5344431042454364
0.6 4 0.5519747727201492
1 2 0.4344818095328392
1 3 0.6473871775367226
Best Paramters:

    Sr  eps  min_pt       sil
0  1.0  0.4     2.0  0.651894

DBSCAN with best params:

In [17]:
clust_DB = DBSCAN(eps=0.4, min_samples=2)
clust_DB.fit(milkscaled.iloc[:,:5])

DBSCAN(eps=0.4, min_samples=2)

### Cluster Analysis

In [7]:
milk_clust = milk.copy()
milk_clust['cluster'] = clust_DB.labels_
milk_clust = milk_clust[milk_clust['cluster'] != -1]
milk_clust.groupby('cluster').mean()

          water    protein        fat   lactose       ash
cluster
0        88.450   1.800000   3.100000  6.200000  0.210000
1        86.825   3.800000   3.275000  5.350000  0.777500
2        81.900   6.033333   6.733333  4.766667  0.873333
3        65.350  10.550000  20.000000  2.550000  1.400000

In [8]:
milk_clust.sort_values('cluster')

           water  protein   fat  lactose   ash  cluster
Animal
ORANGUTAN   88.5      1.4   3.5      6.0  0.24        0
MONKEY      88.4      2.2   2.7      6.4  0.18        0
CAMEL       87.7      3.5   3.4      4.8  0.71        1
BISON       86.9      4.8   1.7      5.7  0.90        1
LLAMA       86.5      3.9   3.2      5.6  0.80        1
ZEBRA       86.2      3.0   4.8      5.3  0.70        1
BUFFALO     82.1      5.9   7.9      4.7  0.78        2
FOX         81.6      6.6   5.9      4.9  0.93        2
SHEEP       82.0      5.6   6.4      4.7  0.91        2
DEER        65.9     10.4  19.7      2.6  1.40        3
REINDEER    64.8     10.7  20.3      2.5  1.40        3

In [9]:
df_clust = pd.DataFrame( {'Animal':list(milkscaled.index), 'cluster':list(clust_DB.labels_) })
df_clust.sort_values('cluster')

        Animal  cluster
0        HORSE       -1
22       WHALE       -1
19         RAT       -1
18      RABBIT       -1
17    ELEPHANT       -1
16         DOG       -1
13         PIG       -1
23        SEAL       -1
9          CAT       -1
12        MULE       -1
4        HIPPO       -1
3       DONKEY       -1
8   GUINEA PIG       -1
24     DOLPHIN       -1
2       MONKEY        0
1    ORANGUTAN        0
11       LLAMA        1
6        BISON        1
14       ZEBRA        1
5        CAMEL        1
10         FOX        2
7      BUFFALO        2
15       SHEEP        2
20        DEER        3
21    REINDEER        3

## USArrests

In [20]:
arrests = pd.read_csv("USArrests.csv",index_col=0)
scaler = StandardScaler().set_output(transform='pandas')
arrests_scaled = scaler.fit_transform(arrests)
clust_DB = DBSCAN(eps=0.4, min_samples=2)
clust_DB.fit(arrests_scaled.iloc[:,:4])
print(clust_DB.labels_)

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1  1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1]

In [22]:
arrests_clust = arrests.copy()
arrests_clust['cluster'] = clust_DB.labels_
arrests_clust = arrests_clust[arrests_clust['cluster'] != -1]
arrests_clust.groupby('cluster').mean()

         Murder  Assault  UrbanPop   Rape
cluster
0         10.75    251.5      84.5  25.05
1          2.15     56.5      56.5  10.40

In [24]:
arrests_clust.sort_values('cluster')

               Murder  Assault  UrbanPop  Rape  cluster
Illinois         10.4      249        83  24.0        0
New York         11.1      254        86  26.1        0
Iowa              2.2       56        57  11.3        1
New Hampshire     2.1       57        56   9.5        1

## Nutrient

In [29]:
nut = pd.read_csv("nutrient.csv", index_col=0)
nut.head(2)

              energy  protein  fat  calcium  iron
Food_Item
BEEF BRAISED     340       20   28        9   2.6
HAMBURGER        245       21   17        9   2.7

In [31]:
scaler = StandardScaler().set_output(transform='pandas')
nut_scaled = scaler.fit_transform(nut)

In [33]:
eps_range = [0.2,0.4,0.6,1]
mp_range = [2,3,4,5]
cnt = 0
a =[]
for i in eps_range:
    for j in mp_range:
        clust_DB = DBSCAN(eps=i, min_samples=j)
        clust_DB.fit(nut_scaled.iloc[:,:5])
        if len(set(clust_DB.labels_)) > 2:
            cnt = cnt + 1
            nut_scaled['Clust'] = clust_DB.labels_
            nut_scl_inliers = nut_scaled[nut_scaled['Clust']!=-1]
            sil_sc = silhouette_score(nut_scl_inliers.iloc[:,:-1],
                             nut_scl_inliers.iloc[:,-1])
            a.append([cnt,i,j,sil_sc])
            print(i,j,sil_sc)
    
a = np.array(a)
pa = pd.DataFrame(a,columns=['Sr','eps','min_pt','sil'])
print("Best Paramters:")
pa[pa['sil'] == pa['sil'].max()]

0.2 2 0.5710837307456811
0.4 2 0.904057085830888
0.6 2 0.7752441663222642
1 2 0.4323695793971159
1 3 0.43147150560271585
Best Paramters:

    Sr  eps  min_pt       sil
1  2.0  0.4     2.0  0.904057

In [39]:
clust_DB = DBSCAN(eps=0.4, min_samples=2)
clust_DB.fit(nut_scaled.iloc[:,:5])
clust_DB.labels_

array([ 0, -1, -1,  0, -1, -1,  1, -1, -1, -1,  0,  0,  0, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1,  1, -1], dtype=int64)

In [41]:
nut_clust = nut.copy()
nut_clust['cluster'] = clust_DB.labels_
nut_clust = nut_clust[nut_clust['cluster'] != -1]
nut_clust.groupby('cluster').mean()

         energy  protein   fat  calcium  iron
cluster
0         350.0     19.4  29.4      9.0  2.52
1         170.0     25.0   7.0      9.5  1.35

In [43]:
nut_clust.sort_values('cluster')

                energy  protein  fat  calcium  iron  cluster
Food_Item
BEEF BRAISED       340       20   28        9   2.6        0
BEEF STEAK         375       19   32        9   2.6        0
SMOKED HAM         340       20   28        9   2.5        0
PORK ROAST         340       19   29        9   2.5        0
PORK SIMMERED      355       19   30        9   2.4        0
CHICKEN CANNED     170       25    7       12   1.5        1
TUNA CANNED        170       25    7        7   1.2        1